#pragma once

#using <mscorlib.dll>
#using <System.dll>
#using <System.Xml.dll>
#using <System.Web.Services.dll>
#using <System.EnterpriseServices.dll>

using namespace System::Security::Permissions;
[assembly:SecurityPermissionAttribute(SecurityAction::RequestMinimum, SkipVerification=false)];
// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 
namespace WsVuelto {
    using namespace System::Diagnostics;
    using namespace System::Web::Services;
    using namespace System::ComponentModel;
    using namespace System::Web::Services::Protocols;
    using namespace System;
    using namespace System::Xml::Serialization;
    using namespace System;
    ref class Supermercado;
    ref class EntidadExterna;
    ref class Movimiento;
    ref class Usuario;
    ref class Respuesta;
    ref class Monto;
    ref class Producto;
    ref class Cajero;
    ref class Cliente;
    ref class operarConVueltoCompletedEventArgs;
    ref class reversarAcreditacionVueltoCompletedEventArgs;
    ref class consultarAcreditacionesCompletedEventArgs;
    ref class consultarDebitosCompletedEventArgs;
    ref class GetDataCompletedEventArgs;
    
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.3038")]
    public delegate System::Void operarConVueltoCompletedEventHandler(System::Object^  sender, WsVuelto::operarConVueltoCompletedEventArgs^  e);
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.3038")]
    public delegate System::Void reversarAcreditacionVueltoCompletedEventHandler(System::Object^  sender, WsVuelto::reversarAcreditacionVueltoCompletedEventArgs^  e);
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.3038")]
    public delegate System::Void consultarAcreditacionesCompletedEventHandler(System::Object^  sender, WsVuelto::consultarAcreditacionesCompletedEventArgs^  e);
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.3038")]
    public delegate System::Void consultarDebitosCompletedEventHandler(System::Object^  sender, WsVuelto::consultarDebitosCompletedEventArgs^  e);
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.3038")]
    public delegate System::Void GetDataCompletedEventHandler(System::Object^  sender, WsVuelto::GetDataCompletedEventArgs^  e);
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.3038"), 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code"), 
    System::Web::Services::WebServiceBindingAttribute(Name=L"BasicHttpBinding_ISupermercado", Namespace=L"http://tempuri.org/")]
    public ref class Supermercado : public System::Web::Services::Protocols::SoapHttpClientProtocol {
        
        private: System::Threading::SendOrPostCallback^  operarConVueltoOperationCompleted;
        
        private: System::Threading::SendOrPostCallback^  reversarAcreditacionVueltoOperationCompleted;
        
        private: System::Threading::SendOrPostCallback^  consultarAcreditacionesOperationCompleted;
        
        private: System::Threading::SendOrPostCallback^  consultarDebitosOperationCompleted;
        
        private: System::Threading::SendOrPostCallback^  GetDataOperationCompleted;
        
        /// <remarks/>
        public: event WsVuelto::operarConVueltoCompletedEventHandler^  operarConVueltoCompleted;
        
        /// <remarks/>
        public: event WsVuelto::reversarAcreditacionVueltoCompletedEventHandler^  reversarAcreditacionVueltoCompleted;
        
        /// <remarks/>
        public: event WsVuelto::consultarAcreditacionesCompletedEventHandler^  consultarAcreditacionesCompleted;
        
        /// <remarks/>
        public: event WsVuelto::consultarDebitosCompletedEventHandler^  consultarDebitosCompleted;
        
        /// <remarks/>
        public: event WsVuelto::GetDataCompletedEventHandler^  GetDataCompleted;
        
        /// <remarks/>
        public: Supermercado();
        /// <remarks/>
        public: [System::Web::Services::Protocols::SoapDocumentMethodAttribute(L"http://tempuri.org/ISupermercado/operarConVuelto", 
            RequestNamespace=L"http://tempuri.org/", ResponseNamespace=L"http://tempuri.org/", Use=System::Web::Services::Description::SoapBindingUse::Literal, 
            ParameterStyle=System::Web::Services::Protocols::SoapParameterStyle::Wrapped)]
        [returnvalue: System::Xml::Serialization::XmlElementAttribute(IsNullable=true)]
        WsVuelto::Respuesta^  operarConVuelto(
                    [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] WsVuelto::EntidadExterna^  entidad, 
                    [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] WsVuelto::Cliente^  cliente, 
                    [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] WsVuelto::Cajero^  cajero, 
                    [System::Xml::Serialization::XmlArrayAttribute(IsNullable=true)] [System::Xml::Serialization::XmlArrayItemAttribute(Namespace=L"http://schemas.datacontract.org/2004/07/WS_Supermercado.model")] 
                    cli::array< WsVuelto::Producto^  >^  consumo, 
                    [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] WsVuelto::Monto^  montoVuelto, 
                    [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] System::String^  codigoAutorizador);
        
        /// <remarks/>
        public: System::IAsyncResult^  BeginoperarConVuelto(
                    WsVuelto::EntidadExterna^  entidad, 
                    WsVuelto::Cliente^  cliente, 
                    WsVuelto::Cajero^  cajero, 
                    cli::array< WsVuelto::Producto^  >^  consumo, 
                    WsVuelto::Monto^  montoVuelto, 
                    System::String^  codigoAutorizador, 
                    System::AsyncCallback^  callback, 
                    System::Object^  asyncState);
        
        /// <remarks/>
        public: WsVuelto::Respuesta^  EndoperarConVuelto(System::IAsyncResult^  asyncResult);
        
        /// <remarks/>
        public: System::Void operarConVueltoAsync(
                    WsVuelto::EntidadExterna^  entidad, 
                    WsVuelto::Cliente^  cliente, 
                    WsVuelto::Cajero^  cajero, 
                    cli::array< WsVuelto::Producto^  >^  consumo, 
                    WsVuelto::Monto^  montoVuelto, 
                    System::String^  codigoAutorizador);
        
        /// <remarks/>
        public: System::Void operarConVueltoAsync(
                    WsVuelto::EntidadExterna^  entidad, 
                    WsVuelto::Cliente^  cliente, 
                    WsVuelto::Cajero^  cajero, 
                    cli::array< WsVuelto::Producto^  >^  consumo, 
                    WsVuelto::Monto^  montoVuelto, 
                    System::String^  codigoAutorizador, 
                    System::Object^  userState);
        
        private: System::Void OnoperarConVueltoOperationCompleted(System::Object^  arg);
        
        /// <remarks/>
        public: [System::Web::Services::Protocols::SoapDocumentMethodAttribute(L"http://tempuri.org/ISupermercado/reversarAcreditacionVuelto", 
            RequestNamespace=L"http://tempuri.org/", ResponseNamespace=L"http://tempuri.org/", Use=System::Web::Services::Description::SoapBindingUse::Literal, 
            ParameterStyle=System::Web::Services::Protocols::SoapParameterStyle::Wrapped)]
        [returnvalue: System::Xml::Serialization::XmlElementAttribute(IsNullable=true)]
        WsVuelto::Respuesta^  reversarAcreditacionVuelto([System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] 
                    WsVuelto::EntidadExterna^  entidad, [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] WsVuelto::Cliente^  cliente, 
                    [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] WsVuelto::Cajero^  cajero);
        
        /// <remarks/>
        public: System::IAsyncResult^  BeginreversarAcreditacionVuelto(WsVuelto::EntidadExterna^  entidad, WsVuelto::Cliente^  cliente, 
                    WsVuelto::Cajero^  cajero, System::AsyncCallback^  callback, System::Object^  asyncState);
        
        /// <remarks/>
        public: WsVuelto::Respuesta^  EndreversarAcreditacionVuelto(System::IAsyncResult^  asyncResult);
        
        /// <remarks/>
        public: System::Void reversarAcreditacionVueltoAsync(WsVuelto::EntidadExterna^  entidad, WsVuelto::Cliente^  cliente, 
                    WsVuelto::Cajero^  cajero);
        
        /// <remarks/>
        public: System::Void reversarAcreditacionVueltoAsync(WsVuelto::EntidadExterna^  entidad, WsVuelto::Cliente^  cliente, 
                    WsVuelto::Cajero^  cajero, System::Object^  userState);
        
        private: System::Void OnreversarAcreditacionVueltoOperationCompleted(System::Object^  arg);
        
        /// <remarks/>
        public: [System::Web::Services::Protocols::SoapDocumentMethodAttribute(L"http://tempuri.org/ISupermercado/consultarAcreditaciones", 
            RequestNamespace=L"http://tempuri.org/", ResponseNamespace=L"http://tempuri.org/", Use=System::Web::Services::Description::SoapBindingUse::Literal, 
            ParameterStyle=System::Web::Services::Protocols::SoapParameterStyle::Wrapped)]
        [returnvalue: System::Xml::Serialization::XmlArrayAttribute(IsNullable=true)]
        [returnvalue: System::Xml::Serialization::XmlArrayItemAttribute(Namespace=L"http://schemas.datacontract.org/2004/07/WS_Supermercado.model")]
        cli::array< WsVuelto::Movimiento^  >^  consultarAcreditaciones(
                    [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] WsVuelto::EntidadExterna^  entidad, 
                    [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] WsVuelto::Usuario^  usuario, 
                    System::DateTime fechaInicio, 
                    [System::Xml::Serialization::XmlIgnoreAttribute] System::Boolean fechaInicioSpecified, 
                    System::DateTime fechaFin, 
                    [System::Xml::Serialization::XmlIgnoreAttribute] System::Boolean fechaFinSpecified);
        
        /// <remarks/>
        public: System::IAsyncResult^  BeginconsultarAcreditaciones(
                    WsVuelto::EntidadExterna^  entidad, 
                    WsVuelto::Usuario^  usuario, 
                    System::DateTime fechaInicio, 
                    System::Boolean fechaInicioSpecified, 
                    System::DateTime fechaFin, 
                    System::Boolean fechaFinSpecified, 
                    System::AsyncCallback^  callback, 
                    System::Object^  asyncState);
        
        /// <remarks/>
        public: cli::array< WsVuelto::Movimiento^  >^  EndconsultarAcreditaciones(System::IAsyncResult^  asyncResult);
        
        /// <remarks/>
        public: System::Void consultarAcreditacionesAsync(
                    WsVuelto::EntidadExterna^  entidad, 
                    WsVuelto::Usuario^  usuario, 
                    System::DateTime fechaInicio, 
                    System::Boolean fechaInicioSpecified, 
                    System::DateTime fechaFin, 
                    System::Boolean fechaFinSpecified);
        
        /// <remarks/>
        public: System::Void consultarAcreditacionesAsync(
                    WsVuelto::EntidadExterna^  entidad, 
                    WsVuelto::Usuario^  usuario, 
                    System::DateTime fechaInicio, 
                    System::Boolean fechaInicioSpecified, 
                    System::DateTime fechaFin, 
                    System::Boolean fechaFinSpecified, 
                    System::Object^  userState);
        
        private: System::Void OnconsultarAcreditacionesOperationCompleted(System::Object^  arg);
        
        /// <remarks/>
        public: [System::Web::Services::Protocols::SoapDocumentMethodAttribute(L"http://tempuri.org/ISupermercado/consultarDebitos", 
            RequestNamespace=L"http://tempuri.org/", ResponseNamespace=L"http://tempuri.org/", Use=System::Web::Services::Description::SoapBindingUse::Literal, 
            ParameterStyle=System::Web::Services::Protocols::SoapParameterStyle::Wrapped)]
        [returnvalue: System::Xml::Serialization::XmlArrayAttribute(IsNullable=true)]
        [returnvalue: System::Xml::Serialization::XmlArrayItemAttribute(Namespace=L"http://schemas.datacontract.org/2004/07/WS_Supermercado.model")]
        cli::array< WsVuelto::Movimiento^  >^  consultarDebitos(
                    [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] WsVuelto::EntidadExterna^  entidad, 
                    [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] WsVuelto::Usuario^  usuario, 
                    System::DateTime fechaInicio, 
                    [System::Xml::Serialization::XmlIgnoreAttribute] System::Boolean fechaInicioSpecified, 
                    System::DateTime fechaFin, 
                    [System::Xml::Serialization::XmlIgnoreAttribute] System::Boolean fechaFinSpecified);
        
        /// <remarks/>
        public: System::IAsyncResult^  BeginconsultarDebitos(
                    WsVuelto::EntidadExterna^  entidad, 
                    WsVuelto::Usuario^  usuario, 
                    System::DateTime fechaInicio, 
                    System::Boolean fechaInicioSpecified, 
                    System::DateTime fechaFin, 
                    System::Boolean fechaFinSpecified, 
                    System::AsyncCallback^  callback, 
                    System::Object^  asyncState);
        
        /// <remarks/>
        public: cli::array< WsVuelto::Movimiento^  >^  EndconsultarDebitos(System::IAsyncResult^  asyncResult);
        
        /// <remarks/>
        public: System::Void consultarDebitosAsync(
                    WsVuelto::EntidadExterna^  entidad, 
                    WsVuelto::Usuario^  usuario, 
                    System::DateTime fechaInicio, 
                    System::Boolean fechaInicioSpecified, 
                    System::DateTime fechaFin, 
                    System::Boolean fechaFinSpecified);
        
        /// <remarks/>
        public: System::Void consultarDebitosAsync(
                    WsVuelto::EntidadExterna^  entidad, 
                    WsVuelto::Usuario^  usuario, 
                    System::DateTime fechaInicio, 
                    System::Boolean fechaInicioSpecified, 
                    System::DateTime fechaFin, 
                    System::Boolean fechaFinSpecified, 
                    System::Object^  userState);
        
        private: System::Void OnconsultarDebitosOperationCompleted(System::Object^  arg);
        
        /// <remarks/>
        public: [System::Web::Services::Protocols::SoapDocumentMethodAttribute(L"http://tempuri.org/ISupermercado/GetData", RequestNamespace=L"http://tempuri.org/", 
            ResponseNamespace=L"http://tempuri.org/", Use=System::Web::Services::Description::SoapBindingUse::Literal, ParameterStyle=System::Web::Services::Protocols::SoapParameterStyle::Wrapped)]
        [returnvalue: System::Xml::Serialization::XmlElementAttribute(IsNullable=true)]
        System::String^  GetData(System::Int32 __identifier(value), [System::Xml::Serialization::XmlIgnoreAttribute] System::Boolean valueSpecified);
        
        /// <remarks/>
        public: System::IAsyncResult^  BeginGetData(System::Int32 __identifier(value), System::Boolean valueSpecified, System::AsyncCallback^  callback, 
                    System::Object^  asyncState);
        
        /// <remarks/>
        public: System::String^  EndGetData(System::IAsyncResult^  asyncResult);
        
        /// <remarks/>
        public: System::Void GetDataAsync(System::Int32 __identifier(value), System::Boolean valueSpecified);
        
        /// <remarks/>
        public: System::Void GetDataAsync(System::Int32 __identifier(value), System::Boolean valueSpecified, System::Object^  userState);
        
        private: System::Void OnGetDataOperationCompleted(System::Object^  arg);
        
        /// <remarks/>
        public: System::Void CancelAsync(System::Object^  userState) new;
    };
    
    /// <comentarios/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.3038"), 
    System::SerializableAttribute, 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code"), 
    System::Xml::Serialization::XmlTypeAttribute(Namespace=L"http://schemas.datacontract.org/2004/07/WS_Supermercado.model")]
    public ref class EntidadExterna {
        
        private: System::String^  claveField;
        
        private: System::String^  cuilField;
        
        private: System::String^  usuarioField;
        
        /// <comentarios/>
        public: [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)]
        property System::String^  Clave {
            System::String^  get();
            System::Void set(System::String^  value);
        }
        
        /// <comentarios/>
        public: [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)]
        property System::String^  Cuil {
            System::String^  get();
            System::Void set(System::String^  value);
        }
        
        /// <comentarios/>
        public: [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)]
        property System::String^  Usuario {
            System::String^  get();
            System::Void set(System::String^  value);
        }
    };
    
    /// <comentarios/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.3038"), 
    System::SerializableAttribute, 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code"), 
    System::Xml::Serialization::XmlTypeAttribute(Namespace=L"http://schemas.datacontract.org/2004/07/WS_Supermercado.model")]
    public ref class Movimiento {
        
        private: System::String^  apellidoNombreField;
        
        private: System::String^  descripcionField;
        
        private: System::DateTime fechaField;
        
        private: System::Boolean fechaFieldSpecified;
        
        private: System::Int32 idMovimientoField;
        
        private: System::Boolean idMovimientoFieldSpecified;
        
        private: System::Int32 idTransaccionField;
        
        private: System::Boolean idTransaccionFieldSpecified;
        
        private: System::Single montoField;
        
        private: System::Boolean montoFieldSpecified;
        
        private: System::String^  tipoMovimientoField;
        
        /// <comentarios/>
        public: [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)]
        property System::String^  ApellidoNombre {
            System::String^  get();
            System::Void set(System::String^  value);
        }
        
        /// <comentarios/>
        public: [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)]
        property System::String^  Descripcion {
            System::String^  get();
            System::Void set(System::String^  value);
        }
        
        /// <comentarios/>
        public: property System::DateTime Fecha {
            System::DateTime get();
            System::Void set(System::DateTime value);
        }
        
        /// <comentarios/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean FechaSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <comentarios/>
        public: property System::Int32 IdMovimiento {
            System::Int32 get();
            System::Void set(System::Int32 value);
        }
        
        /// <comentarios/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean IdMovimientoSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <comentarios/>
        public: property System::Int32 IdTransaccion {
            System::Int32 get();
            System::Void set(System::Int32 value);
        }
        
        /// <comentarios/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean IdTransaccionSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <comentarios/>
        public: property System::Single Monto {
            System::Single get();
            System::Void set(System::Single value);
        }
        
        /// <comentarios/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean MontoSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <comentarios/>
        public: [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)]
        property System::String^  TipoMovimiento {
            System::String^  get();
            System::Void set(System::String^  value);
        }
    };
    
    /// <comentarios/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.3038"), 
    System::SerializableAttribute, 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code"), 
    System::Xml::Serialization::XmlTypeAttribute(Namespace=L"http://schemas.datacontract.org/2004/07/WS_Supermercado.model")]
    public ref class Usuario {
        
        private: System::String^  identificadorField;
        
        private: System::String^  nombreUsuarioField;
        
        /// <comentarios/>
        public: [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)]
        property System::String^  Identificador {
            System::String^  get();
            System::Void set(System::String^  value);
        }
        
        /// <comentarios/>
        public: [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)]
        property System::String^  NombreUsuario {
            System::String^  get();
            System::Void set(System::String^  value);
        }
    };
    
    /// <comentarios/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.3038"), 
    System::SerializableAttribute, 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code"), 
    System::Xml::Serialization::XmlTypeAttribute(Namespace=L"http://schemas.datacontract.org/2004/07/WS_Supermercado.model")]
    public ref class Respuesta {
        
        private: System::Int64 codigoErrorField;
        
        private: System::Boolean codigoErrorFieldSpecified;
        
        private: System::String^  descripcionField;
        
        private: System::Int64 idTransaccionField;
        
        private: System::Boolean idTransaccionFieldSpecified;
        
        /// <comentarios/>
        public: property System::Int64 CodigoError {
            System::Int64 get();
            System::Void set(System::Int64 value);
        }
        
        /// <comentarios/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean CodigoErrorSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <comentarios/>
        public: [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)]
        property System::String^  Descripcion {
            System::String^  get();
            System::Void set(System::String^  value);
        }
        
        /// <comentarios/>
        public: property System::Int64 IdTransaccion {
            System::Int64 get();
            System::Void set(System::Int64 value);
        }
        
        /// <comentarios/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean IdTransaccionSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
    };
    
    /// <comentarios/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.3038"), 
    System::SerializableAttribute, 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code"), 
    System::Xml::Serialization::XmlTypeAttribute(Namespace=L"http://schemas.datacontract.org/2004/07/WS_Supermercado.model")]
    public ref class Monto {
        
        private: System::Single montoVueltoField;
        
        private: System::Boolean montoVueltoFieldSpecified;
        
        private: System::String^  tipoMonedaField;
        
        private: System::String^  tipoOperacionField;
        
        /// <comentarios/>
        public: property System::Single MontoVuelto {
            System::Single get();
            System::Void set(System::Single value);
        }
        
        /// <comentarios/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean MontoVueltoSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <comentarios/>
        public: [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)]
        property System::String^  TipoMoneda {
            System::String^  get();
            System::Void set(System::String^  value);
        }
        
        /// <comentarios/>
        public: [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)]
        property System::String^  TipoOperacion {
            System::String^  get();
            System::Void set(System::String^  value);
        }
    };
    
    /// <comentarios/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.3038"), 
    System::SerializableAttribute, 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code"), 
    System::Xml::Serialization::XmlTypeAttribute(Namespace=L"http://schemas.datacontract.org/2004/07/WS_Supermercado.model")]
    public ref class Producto {
        
        private: System::Int32 cantidadField;
        
        private: System::Boolean cantidadFieldSpecified;
        
        private: System::String^  identificadorField;
        
        private: System::String^  marcaField;
        
        private: System::String^  nombreField;
        
        private: System::Single precioUnitarioField;
        
        private: System::Boolean precioUnitarioFieldSpecified;
        
        private: System::String^  rubroField;
        
        /// <comentarios/>
        public: property System::Int32 Cantidad {
            System::Int32 get();
            System::Void set(System::Int32 value);
        }
        
        /// <comentarios/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean CantidadSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <comentarios/>
        public: [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)]
        property System::String^  Identificador {
            System::String^  get();
            System::Void set(System::String^  value);
        }
        
        /// <comentarios/>
        public: [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)]
        property System::String^  Marca {
            System::String^  get();
            System::Void set(System::String^  value);
        }
        
        /// <comentarios/>
        public: [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)]
        property System::String^  Nombre {
            System::String^  get();
            System::Void set(System::String^  value);
        }
        
        /// <comentarios/>
        public: property System::Single PrecioUnitario {
            System::Single get();
            System::Void set(System::Single value);
        }
        
        /// <comentarios/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean PrecioUnitarioSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <comentarios/>
        public: [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)]
        property System::String^  Rubro {
            System::String^  get();
            System::Void set(System::String^  value);
        }
    };
    
    /// <comentarios/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.3038"), 
    System::SerializableAttribute, 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code"), 
    System::Xml::Serialization::XmlTypeAttribute(Namespace=L"http://schemas.datacontract.org/2004/07/WS_Supermercado.model")]
    public ref class Cajero {
        
        private: System::String^  fechaOperacionField;
        
        private: System::String^  idCajaField;
        
        private: System::String^  idSucursalField;
        
        private: System::String^  identificadorField;
        
        /// <comentarios/>
        public: [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)]
        property System::String^  FechaOperacion {
            System::String^  get();
            System::Void set(System::String^  value);
        }
        
        /// <comentarios/>
        public: [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)]
        property System::String^  IdCaja {
            System::String^  get();
            System::Void set(System::String^  value);
        }
        
        /// <comentarios/>
        public: [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)]
        property System::String^  IdSucursal {
            System::String^  get();
            System::Void set(System::String^  value);
        }
        
        /// <comentarios/>
        public: [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)]
        property System::String^  Identificador {
            System::String^  get();
            System::Void set(System::String^  value);
        }
    };
    
    /// <comentarios/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.3038"), 
    System::SerializableAttribute, 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code"), 
    System::Xml::Serialization::XmlTypeAttribute(Namespace=L"http://schemas.datacontract.org/2004/07/WS_Supermercado.model")]
    public ref class Cliente {
        
        private: System::String^  apellidoField;
        
        private: System::String^  celularField;
        
        private: System::String^  dniField;
        
        private: System::String^  nombreField;
        
        /// <comentarios/>
        public: [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)]
        property System::String^  Apellido {
            System::String^  get();
            System::Void set(System::String^  value);
        }
        
        /// <comentarios/>
        public: [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)]
        property System::String^  Celular {
            System::String^  get();
            System::Void set(System::String^  value);
        }
        
        /// <comentarios/>
        public: [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)]
        property System::String^  Dni {
            System::String^  get();
            System::Void set(System::String^  value);
        }
        
        /// <comentarios/>
        public: [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)]
        property System::String^  Nombre {
            System::String^  get();
            System::Void set(System::String^  value);
        }
    };
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.3038"), 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code")]
    public ref class operarConVueltoCompletedEventArgs : public System::ComponentModel::AsyncCompletedEventArgs {
        
        private: cli::array< System::Object^  >^  results;
        
        internal: operarConVueltoCompletedEventArgs(cli::array< System::Object^  >^  results, System::Exception^  exception, 
                    System::Boolean cancelled, System::Object^  userState);
        /// <remarks/>
        public: property WsVuelto::Respuesta^  Result {
            WsVuelto::Respuesta^  get();
        }
    };
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.3038"), 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code")]
    public ref class reversarAcreditacionVueltoCompletedEventArgs : public System::ComponentModel::AsyncCompletedEventArgs {
        
        private: cli::array< System::Object^  >^  results;
        
        internal: reversarAcreditacionVueltoCompletedEventArgs(cli::array< System::Object^  >^  results, System::Exception^  exception, 
                    System::Boolean cancelled, System::Object^  userState);
        /// <remarks/>
        public: property WsVuelto::Respuesta^  Result {
            WsVuelto::Respuesta^  get();
        }
    };
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.3038"), 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code")]
    public ref class consultarAcreditacionesCompletedEventArgs : public System::ComponentModel::AsyncCompletedEventArgs {
        
        private: cli::array< System::Object^  >^  results;
        
        internal: consultarAcreditacionesCompletedEventArgs(cli::array< System::Object^  >^  results, System::Exception^  exception, 
                    System::Boolean cancelled, System::Object^  userState);
        /// <remarks/>
        public: property cli::array< WsVuelto::Movimiento^  >^  Result {
            cli::array< WsVuelto::Movimiento^  >^  get();
        }
    };
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.3038"), 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code")]
    public ref class consultarDebitosCompletedEventArgs : public System::ComponentModel::AsyncCompletedEventArgs {
        
        private: cli::array< System::Object^  >^  results;
        
        internal: consultarDebitosCompletedEventArgs(cli::array< System::Object^  >^  results, System::Exception^  exception, 
                    System::Boolean cancelled, System::Object^  userState);
        /// <remarks/>
        public: property cli::array< WsVuelto::Movimiento^  >^  Result {
            cli::array< WsVuelto::Movimiento^  >^  get();
        }
    };
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.3038"), 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code")]
    public ref class GetDataCompletedEventArgs : public System::ComponentModel::AsyncCompletedEventArgs {
        
        private: cli::array< System::Object^  >^  results;
        
        internal: GetDataCompletedEventArgs(cli::array< System::Object^  >^  results, System::Exception^  exception, System::Boolean cancelled, 
                    System::Object^  userState);
        /// <remarks/>
        public: property System::String^  Result {
            System::String^  get();
        }
    };
}
namespace WsVuelto {
    
    
    inline Supermercado::Supermercado() {
        this->Url = L"http://190.137.162.9/ServiceSupermercado/Service.svc/WS_Supermercado";
    }
    
    inline WsVuelto::Respuesta^  Supermercado::operarConVuelto(
                [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] WsVuelto::EntidadExterna^  entidad, 
                [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] WsVuelto::Cliente^  cliente, 
                [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] WsVuelto::Cajero^  cajero, 
                [System::Xml::Serialization::XmlArrayAttribute(IsNullable=true)] [System::Xml::Serialization::XmlArrayItemAttribute(Namespace=L"http://schemas.datacontract.org/2004/07/WS_Supermercado.model")] 
                cli::array< WsVuelto::Producto^  >^  consumo, 
                [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] WsVuelto::Monto^  montoVuelto, 
                [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] System::String^  codigoAutorizador) {
        cli::array< System::Object^  >^  results = this->Invoke(L"operarConVuelto", gcnew cli::array< System::Object^  >(6) {entidad, 
                cliente, cajero, consumo, montoVuelto, codigoAutorizador});
        return (cli::safe_cast<WsVuelto::Respuesta^  >(results[0]));
    }
    
    inline System::IAsyncResult^  Supermercado::BeginoperarConVuelto(
                WsVuelto::EntidadExterna^  entidad, 
                WsVuelto::Cliente^  cliente, 
                WsVuelto::Cajero^  cajero, 
                cli::array< WsVuelto::Producto^  >^  consumo, 
                WsVuelto::Monto^  montoVuelto, 
                System::String^  codigoAutorizador, 
                System::AsyncCallback^  callback, 
                System::Object^  asyncState) {
        return this->BeginInvoke(L"operarConVuelto", gcnew cli::array< System::Object^  >(6) {entidad, cliente, cajero, consumo, 
                montoVuelto, codigoAutorizador}, callback, asyncState);
    }
    
    inline WsVuelto::Respuesta^  Supermercado::EndoperarConVuelto(System::IAsyncResult^  asyncResult) {
        cli::array< System::Object^  >^  results = this->EndInvoke(asyncResult);
        return (cli::safe_cast<WsVuelto::Respuesta^  >(results[0]));
    }
    
    inline System::Void Supermercado::operarConVueltoAsync(
                WsVuelto::EntidadExterna^  entidad, 
                WsVuelto::Cliente^  cliente, 
                WsVuelto::Cajero^  cajero, 
                cli::array< WsVuelto::Producto^  >^  consumo, 
                WsVuelto::Monto^  montoVuelto, 
                System::String^  codigoAutorizador) {
        this->operarConVueltoAsync(entidad, cliente, cajero, consumo, montoVuelto, codigoAutorizador, nullptr);
    }
    
    inline System::Void Supermercado::operarConVueltoAsync(
                WsVuelto::EntidadExterna^  entidad, 
                WsVuelto::Cliente^  cliente, 
                WsVuelto::Cajero^  cajero, 
                cli::array< WsVuelto::Producto^  >^  consumo, 
                WsVuelto::Monto^  montoVuelto, 
                System::String^  codigoAutorizador, 
                System::Object^  userState) {
        if (this->operarConVueltoOperationCompleted == nullptr) {
            this->operarConVueltoOperationCompleted = gcnew System::Threading::SendOrPostCallback(this, &WsVuelto::Supermercado::OnoperarConVueltoOperationCompleted);
        }
        this->InvokeAsync(L"operarConVuelto", gcnew cli::array< System::Object^  >(6) {entidad, cliente, cajero, consumo, 
                montoVuelto, codigoAutorizador}, this->operarConVueltoOperationCompleted, userState);
    }
    
    inline System::Void Supermercado::OnoperarConVueltoOperationCompleted(System::Object^  arg) {
        {
            System::Web::Services::Protocols::InvokeCompletedEventArgs^  invokeArgs = (cli::safe_cast<System::Web::Services::Protocols::InvokeCompletedEventArgs^  >(arg));
            this->operarConVueltoCompleted(this, (gcnew WsVuelto::operarConVueltoCompletedEventArgs(invokeArgs->Results, invokeArgs->Error, 
                    invokeArgs->Cancelled, invokeArgs->UserState)));
        }
    }
    
    inline WsVuelto::Respuesta^  Supermercado::reversarAcreditacionVuelto([System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] 
                WsVuelto::EntidadExterna^  entidad, [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] WsVuelto::Cliente^  cliente, 
                [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] WsVuelto::Cajero^  cajero) {
        cli::array< System::Object^  >^  results = this->Invoke(L"reversarAcreditacionVuelto", gcnew cli::array< System::Object^  >(3) {entidad, 
                cliente, cajero});
        return (cli::safe_cast<WsVuelto::Respuesta^  >(results[0]));
    }
    
    inline System::IAsyncResult^  Supermercado::BeginreversarAcreditacionVuelto(WsVuelto::EntidadExterna^  entidad, WsVuelto::Cliente^  cliente, 
                WsVuelto::Cajero^  cajero, System::AsyncCallback^  callback, System::Object^  asyncState) {
        return this->BeginInvoke(L"reversarAcreditacionVuelto", gcnew cli::array< System::Object^  >(3) {entidad, cliente, 
                cajero}, callback, asyncState);
    }
    
    inline WsVuelto::Respuesta^  Supermercado::EndreversarAcreditacionVuelto(System::IAsyncResult^  asyncResult) {
        cli::array< System::Object^  >^  results = this->EndInvoke(asyncResult);
        return (cli::safe_cast<WsVuelto::Respuesta^  >(results[0]));
    }
    
    inline System::Void Supermercado::reversarAcreditacionVueltoAsync(WsVuelto::EntidadExterna^  entidad, WsVuelto::Cliente^  cliente, 
                WsVuelto::Cajero^  cajero) {
        this->reversarAcreditacionVueltoAsync(entidad, cliente, cajero, nullptr);
    }
    
    inline System::Void Supermercado::reversarAcreditacionVueltoAsync(WsVuelto::EntidadExterna^  entidad, WsVuelto::Cliente^  cliente, 
                WsVuelto::Cajero^  cajero, System::Object^  userState) {
        if (this->reversarAcreditacionVueltoOperationCompleted == nullptr) {
            this->reversarAcreditacionVueltoOperationCompleted = gcnew System::Threading::SendOrPostCallback(this, &WsVuelto::Supermercado::OnreversarAcreditacionVueltoOperationCompleted);
        }
        this->InvokeAsync(L"reversarAcreditacionVuelto", gcnew cli::array< System::Object^  >(3) {entidad, cliente, cajero}, 
            this->reversarAcreditacionVueltoOperationCompleted, userState);
    }
    
    inline System::Void Supermercado::OnreversarAcreditacionVueltoOperationCompleted(System::Object^  arg) {
        {
            System::Web::Services::Protocols::InvokeCompletedEventArgs^  invokeArgs = (cli::safe_cast<System::Web::Services::Protocols::InvokeCompletedEventArgs^  >(arg));
            this->reversarAcreditacionVueltoCompleted(this, (gcnew WsVuelto::reversarAcreditacionVueltoCompletedEventArgs(invokeArgs->Results, 
                    invokeArgs->Error, invokeArgs->Cancelled, invokeArgs->UserState)));
        }
    }
    
    inline cli::array< WsVuelto::Movimiento^  >^  Supermercado::consultarAcreditaciones(
                [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] WsVuelto::EntidadExterna^  entidad, 
                [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] WsVuelto::Usuario^  usuario, 
                System::DateTime fechaInicio, 
                [System::Xml::Serialization::XmlIgnoreAttribute] System::Boolean fechaInicioSpecified, 
                System::DateTime fechaFin, 
                [System::Xml::Serialization::XmlIgnoreAttribute] System::Boolean fechaFinSpecified) {
        cli::array< System::Object^  >^  results = this->Invoke(L"consultarAcreditaciones", gcnew cli::array< System::Object^  >(6) {entidad, 
                usuario, fechaInicio, fechaInicioSpecified, fechaFin, fechaFinSpecified});
        return (cli::safe_cast<cli::array< WsVuelto::Movimiento^  >^  >(results[0]));
    }
    
    inline System::IAsyncResult^  Supermercado::BeginconsultarAcreditaciones(
                WsVuelto::EntidadExterna^  entidad, 
                WsVuelto::Usuario^  usuario, 
                System::DateTime fechaInicio, 
                System::Boolean fechaInicioSpecified, 
                System::DateTime fechaFin, 
                System::Boolean fechaFinSpecified, 
                System::AsyncCallback^  callback, 
                System::Object^  asyncState) {
        return this->BeginInvoke(L"consultarAcreditaciones", gcnew cli::array< System::Object^  >(6) {entidad, usuario, fechaInicio, 
                fechaInicioSpecified, fechaFin, fechaFinSpecified}, callback, asyncState);
    }
    
    inline cli::array< WsVuelto::Movimiento^  >^  Supermercado::EndconsultarAcreditaciones(System::IAsyncResult^  asyncResult) {
        cli::array< System::Object^  >^  results = this->EndInvoke(asyncResult);
        return (cli::safe_cast<cli::array< WsVuelto::Movimiento^  >^  >(results[0]));
    }
    
    inline System::Void Supermercado::consultarAcreditacionesAsync(
                WsVuelto::EntidadExterna^  entidad, 
                WsVuelto::Usuario^  usuario, 
                System::DateTime fechaInicio, 
                System::Boolean fechaInicioSpecified, 
                System::DateTime fechaFin, 
                System::Boolean fechaFinSpecified) {
        this->consultarAcreditacionesAsync(entidad, usuario, fechaInicio, fechaInicioSpecified, fechaFin, fechaFinSpecified, nullptr);
    }
    
    inline System::Void Supermercado::consultarAcreditacionesAsync(
                WsVuelto::EntidadExterna^  entidad, 
                WsVuelto::Usuario^  usuario, 
                System::DateTime fechaInicio, 
                System::Boolean fechaInicioSpecified, 
                System::DateTime fechaFin, 
                System::Boolean fechaFinSpecified, 
                System::Object^  userState) {
        if (this->consultarAcreditacionesOperationCompleted == nullptr) {
            this->consultarAcreditacionesOperationCompleted = gcnew System::Threading::SendOrPostCallback(this, &WsVuelto::Supermercado::OnconsultarAcreditacionesOperationCompleted);
        }
        this->InvokeAsync(L"consultarAcreditaciones", gcnew cli::array< System::Object^  >(6) {entidad, usuario, fechaInicio, 
                fechaInicioSpecified, fechaFin, fechaFinSpecified}, this->consultarAcreditacionesOperationCompleted, userState);
    }
    
    inline System::Void Supermercado::OnconsultarAcreditacionesOperationCompleted(System::Object^  arg) {
        {
            System::Web::Services::Protocols::InvokeCompletedEventArgs^  invokeArgs = (cli::safe_cast<System::Web::Services::Protocols::InvokeCompletedEventArgs^  >(arg));
            this->consultarAcreditacionesCompleted(this, (gcnew WsVuelto::consultarAcreditacionesCompletedEventArgs(invokeArgs->Results, 
                    invokeArgs->Error, invokeArgs->Cancelled, invokeArgs->UserState)));
        }
    }
    
    inline cli::array< WsVuelto::Movimiento^  >^  Supermercado::consultarDebitos(
                [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] WsVuelto::EntidadExterna^  entidad, 
                [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)] WsVuelto::Usuario^  usuario, 
                System::DateTime fechaInicio, 
                [System::Xml::Serialization::XmlIgnoreAttribute] System::Boolean fechaInicioSpecified, 
                System::DateTime fechaFin, 
                [System::Xml::Serialization::XmlIgnoreAttribute] System::Boolean fechaFinSpecified) {
        cli::array< System::Object^  >^  results = this->Invoke(L"consultarDebitos", gcnew cli::array< System::Object^  >(6) {entidad, 
                usuario, fechaInicio, fechaInicioSpecified, fechaFin, fechaFinSpecified});
        return (cli::safe_cast<cli::array< WsVuelto::Movimiento^  >^  >(results[0]));
    }
    
    inline System::IAsyncResult^  Supermercado::BeginconsultarDebitos(
                WsVuelto::EntidadExterna^  entidad, 
                WsVuelto::Usuario^  usuario, 
                System::DateTime fechaInicio, 
                System::Boolean fechaInicioSpecified, 
                System::DateTime fechaFin, 
                System::Boolean fechaFinSpecified, 
                System::AsyncCallback^  callback, 
                System::Object^  asyncState) {
        return this->BeginInvoke(L"consultarDebitos", gcnew cli::array< System::Object^  >(6) {entidad, usuario, fechaInicio, 
                fechaInicioSpecified, fechaFin, fechaFinSpecified}, callback, asyncState);
    }
    
    inline cli::array< WsVuelto::Movimiento^  >^  Supermercado::EndconsultarDebitos(System::IAsyncResult^  asyncResult) {
        cli::array< System::Object^  >^  results = this->EndInvoke(asyncResult);
        return (cli::safe_cast<cli::array< WsVuelto::Movimiento^  >^  >(results[0]));
    }
    
    inline System::Void Supermercado::consultarDebitosAsync(
                WsVuelto::EntidadExterna^  entidad, 
                WsVuelto::Usuario^  usuario, 
                System::DateTime fechaInicio, 
                System::Boolean fechaInicioSpecified, 
                System::DateTime fechaFin, 
                System::Boolean fechaFinSpecified) {
        this->consultarDebitosAsync(entidad, usuario, fechaInicio, fechaInicioSpecified, fechaFin, fechaFinSpecified, nullptr);
    }
    
    inline System::Void Supermercado::consultarDebitosAsync(
                WsVuelto::EntidadExterna^  entidad, 
                WsVuelto::Usuario^  usuario, 
                System::DateTime fechaInicio, 
                System::Boolean fechaInicioSpecified, 
                System::DateTime fechaFin, 
                System::Boolean fechaFinSpecified, 
                System::Object^  userState) {
        if (this->consultarDebitosOperationCompleted == nullptr) {
            this->consultarDebitosOperationCompleted = gcnew System::Threading::SendOrPostCallback(this, &WsVuelto::Supermercado::OnconsultarDebitosOperationCompleted);
        }
        this->InvokeAsync(L"consultarDebitos", gcnew cli::array< System::Object^  >(6) {entidad, usuario, fechaInicio, fechaInicioSpecified, 
                fechaFin, fechaFinSpecified}, this->consultarDebitosOperationCompleted, userState);
    }
    
    inline System::Void Supermercado::OnconsultarDebitosOperationCompleted(System::Object^  arg) {
        {
            System::Web::Services::Protocols::InvokeCompletedEventArgs^  invokeArgs = (cli::safe_cast<System::Web::Services::Protocols::InvokeCompletedEventArgs^  >(arg));
            this->consultarDebitosCompleted(this, (gcnew WsVuelto::consultarDebitosCompletedEventArgs(invokeArgs->Results, invokeArgs->Error, 
                    invokeArgs->Cancelled, invokeArgs->UserState)));
        }
    }
    
    inline System::String^  Supermercado::GetData(System::Int32 __identifier(value), [System::Xml::Serialization::XmlIgnoreAttribute] 
                System::Boolean valueSpecified) {
        cli::array< System::Object^  >^  results = this->Invoke(L"GetData", gcnew cli::array< System::Object^  >(2) {__identifier(value), 
                valueSpecified});
        return (cli::safe_cast<System::String^  >(results[0]));
    }
    
    inline System::IAsyncResult^  Supermercado::BeginGetData(System::Int32 __identifier(value), System::Boolean valueSpecified, 
                System::AsyncCallback^  callback, System::Object^  asyncState) {
        return this->BeginInvoke(L"GetData", gcnew cli::array< System::Object^  >(2) {__identifier(value), valueSpecified}, callback, 
            asyncState);
    }
    
    inline System::String^  Supermercado::EndGetData(System::IAsyncResult^  asyncResult) {
        cli::array< System::Object^  >^  results = this->EndInvoke(asyncResult);
        return (cli::safe_cast<System::String^  >(results[0]));
    }
    
    inline System::Void Supermercado::GetDataAsync(System::Int32 __identifier(value), System::Boolean valueSpecified) {
        this->GetDataAsync(__identifier(value), valueSpecified, nullptr);
    }
    
    inline System::Void Supermercado::GetDataAsync(System::Int32 __identifier(value), System::Boolean valueSpecified, System::Object^  userState) {
        if (this->GetDataOperationCompleted == nullptr) {
            this->GetDataOperationCompleted = gcnew System::Threading::SendOrPostCallback(this, &WsVuelto::Supermercado::OnGetDataOperationCompleted);
        }
        this->InvokeAsync(L"GetData", gcnew cli::array< System::Object^  >(2) {__identifier(value), valueSpecified}, this->GetDataOperationCompleted, 
            userState);
    }
    
    inline System::Void Supermercado::OnGetDataOperationCompleted(System::Object^  arg) {
        {
            System::Web::Services::Protocols::InvokeCompletedEventArgs^  invokeArgs = (cli::safe_cast<System::Web::Services::Protocols::InvokeCompletedEventArgs^  >(arg));
            this->GetDataCompleted(this, (gcnew WsVuelto::GetDataCompletedEventArgs(invokeArgs->Results, invokeArgs->Error, invokeArgs->Cancelled, 
                    invokeArgs->UserState)));
        }
    }
    
    inline System::Void Supermercado::CancelAsync(System::Object^  userState) {
        __super::CancelAsync(userState);
    }
    
    
    inline System::String^  EntidadExterna::Clave::get() {
        return this->claveField;
    }
    inline System::Void EntidadExterna::Clave::set(System::String^  value) {
        this->claveField = value;
    }
    
    inline System::String^  EntidadExterna::Cuil::get() {
        return this->cuilField;
    }
    inline System::Void EntidadExterna::Cuil::set(System::String^  value) {
        this->cuilField = value;
    }
    
    inline System::String^  EntidadExterna::Usuario::get() {
        return this->usuarioField;
    }
    inline System::Void EntidadExterna::Usuario::set(System::String^  value) {
        this->usuarioField = value;
    }
    
    
    inline System::String^  Movimiento::ApellidoNombre::get() {
        return this->apellidoNombreField;
    }
    inline System::Void Movimiento::ApellidoNombre::set(System::String^  value) {
        this->apellidoNombreField = value;
    }
    
    inline System::String^  Movimiento::Descripcion::get() {
        return this->descripcionField;
    }
    inline System::Void Movimiento::Descripcion::set(System::String^  value) {
        this->descripcionField = value;
    }
    
    inline System::DateTime Movimiento::Fecha::get() {
        return this->fechaField;
    }
    inline System::Void Movimiento::Fecha::set(System::DateTime value) {
        this->fechaField = value;
    }
    
    inline System::Boolean Movimiento::FechaSpecified::get() {
        return this->fechaFieldSpecified;
    }
    inline System::Void Movimiento::FechaSpecified::set(System::Boolean value) {
        this->fechaFieldSpecified = value;
    }
    
    inline System::Int32 Movimiento::IdMovimiento::get() {
        return this->idMovimientoField;
    }
    inline System::Void Movimiento::IdMovimiento::set(System::Int32 value) {
        this->idMovimientoField = value;
    }
    
    inline System::Boolean Movimiento::IdMovimientoSpecified::get() {
        return this->idMovimientoFieldSpecified;
    }
    inline System::Void Movimiento::IdMovimientoSpecified::set(System::Boolean value) {
        this->idMovimientoFieldSpecified = value;
    }
    
    inline System::Int32 Movimiento::IdTransaccion::get() {
        return this->idTransaccionField;
    }
    inline System::Void Movimiento::IdTransaccion::set(System::Int32 value) {
        this->idTransaccionField = value;
    }
    
    inline System::Boolean Movimiento::IdTransaccionSpecified::get() {
        return this->idTransaccionFieldSpecified;
    }
    inline System::Void Movimiento::IdTransaccionSpecified::set(System::Boolean value) {
        this->idTransaccionFieldSpecified = value;
    }
    
    inline System::Single Movimiento::Monto::get() {
        return this->montoField;
    }
    inline System::Void Movimiento::Monto::set(System::Single value) {
        this->montoField = value;
    }
    
    inline System::Boolean Movimiento::MontoSpecified::get() {
        return this->montoFieldSpecified;
    }
    inline System::Void Movimiento::MontoSpecified::set(System::Boolean value) {
        this->montoFieldSpecified = value;
    }
    
    inline System::String^  Movimiento::TipoMovimiento::get() {
        return this->tipoMovimientoField;
    }
    inline System::Void Movimiento::TipoMovimiento::set(System::String^  value) {
        this->tipoMovimientoField = value;
    }
    
    
    inline System::String^  Usuario::Identificador::get() {
        return this->identificadorField;
    }
    inline System::Void Usuario::Identificador::set(System::String^  value) {
        this->identificadorField = value;
    }
    
    inline System::String^  Usuario::NombreUsuario::get() {
        return this->nombreUsuarioField;
    }
    inline System::Void Usuario::NombreUsuario::set(System::String^  value) {
        this->nombreUsuarioField = value;
    }
    
    
    inline System::Int64 Respuesta::CodigoError::get() {
        return this->codigoErrorField;
    }
    inline System::Void Respuesta::CodigoError::set(System::Int64 value) {
        this->codigoErrorField = value;
    }
    
    inline System::Boolean Respuesta::CodigoErrorSpecified::get() {
        return this->codigoErrorFieldSpecified;
    }
    inline System::Void Respuesta::CodigoErrorSpecified::set(System::Boolean value) {
        this->codigoErrorFieldSpecified = value;
    }
    
    inline System::String^  Respuesta::Descripcion::get() {
        return this->descripcionField;
    }
    inline System::Void Respuesta::Descripcion::set(System::String^  value) {
        this->descripcionField = value;
    }
    
    inline System::Int64 Respuesta::IdTransaccion::get() {
        return this->idTransaccionField;
    }
    inline System::Void Respuesta::IdTransaccion::set(System::Int64 value) {
        this->idTransaccionField = value;
    }
    
    inline System::Boolean Respuesta::IdTransaccionSpecified::get() {
        return this->idTransaccionFieldSpecified;
    }
    inline System::Void Respuesta::IdTransaccionSpecified::set(System::Boolean value) {
        this->idTransaccionFieldSpecified = value;
    }
    
    
    inline System::Single Monto::MontoVuelto::get() {
        return this->montoVueltoField;
    }
    inline System::Void Monto::MontoVuelto::set(System::Single value) {
        this->montoVueltoField = value;
    }
    
    inline System::Boolean Monto::MontoVueltoSpecified::get() {
        return this->montoVueltoFieldSpecified;
    }
    inline System::Void Monto::MontoVueltoSpecified::set(System::Boolean value) {
        this->montoVueltoFieldSpecified = value;
    }
    
    inline System::String^  Monto::TipoMoneda::get() {
        return this->tipoMonedaField;
    }
    inline System::Void Monto::TipoMoneda::set(System::String^  value) {
        this->tipoMonedaField = value;
    }
    
    inline System::String^  Monto::TipoOperacion::get() {
        return this->tipoOperacionField;
    }
    inline System::Void Monto::TipoOperacion::set(System::String^  value) {
        this->tipoOperacionField = value;
    }
    
    
    inline System::Int32 Producto::Cantidad::get() {
        return this->cantidadField;
    }
    inline System::Void Producto::Cantidad::set(System::Int32 value) {
        this->cantidadField = value;
    }
    
    inline System::Boolean Producto::CantidadSpecified::get() {
        return this->cantidadFieldSpecified;
    }
    inline System::Void Producto::CantidadSpecified::set(System::Boolean value) {
        this->cantidadFieldSpecified = value;
    }
    
    inline System::String^  Producto::Identificador::get() {
        return this->identificadorField;
    }
    inline System::Void Producto::Identificador::set(System::String^  value) {
        this->identificadorField = value;
    }
    
    inline System::String^  Producto::Marca::get() {
        return this->marcaField;
    }
    inline System::Void Producto::Marca::set(System::String^  value) {
        this->marcaField = value;
    }
    
    inline System::String^  Producto::Nombre::get() {
        return this->nombreField;
    }
    inline System::Void Producto::Nombre::set(System::String^  value) {
        this->nombreField = value;
    }
    
    inline System::Single Producto::PrecioUnitario::get() {
        return this->precioUnitarioField;
    }
    inline System::Void Producto::PrecioUnitario::set(System::Single value) {
        this->precioUnitarioField = value;
    }
    
    inline System::Boolean Producto::PrecioUnitarioSpecified::get() {
        return this->precioUnitarioFieldSpecified;
    }
    inline System::Void Producto::PrecioUnitarioSpecified::set(System::Boolean value) {
        this->precioUnitarioFieldSpecified = value;
    }
    
    inline System::String^  Producto::Rubro::get() {
        return this->rubroField;
    }
    inline System::Void Producto::Rubro::set(System::String^  value) {
        this->rubroField = value;
    }
    
    
    inline System::String^  Cajero::FechaOperacion::get() {
        return this->fechaOperacionField;
    }
    inline System::Void Cajero::FechaOperacion::set(System::String^  value) {
        this->fechaOperacionField = value;
    }
    
    inline System::String^  Cajero::IdCaja::get() {
        return this->idCajaField;
    }
    inline System::Void Cajero::IdCaja::set(System::String^  value) {
        this->idCajaField = value;
    }
    
    inline System::String^  Cajero::IdSucursal::get() {
        return this->idSucursalField;
    }
    inline System::Void Cajero::IdSucursal::set(System::String^  value) {
        this->idSucursalField = value;
    }
    
    inline System::String^  Cajero::Identificador::get() {
        return this->identificadorField;
    }
    inline System::Void Cajero::Identificador::set(System::String^  value) {
        this->identificadorField = value;
    }
    
    
    inline System::String^  Cliente::Apellido::get() {
        return this->apellidoField;
    }
    inline System::Void Cliente::Apellido::set(System::String^  value) {
        this->apellidoField = value;
    }
    
    inline System::String^  Cliente::Celular::get() {
        return this->celularField;
    }
    inline System::Void Cliente::Celular::set(System::String^  value) {
        this->celularField = value;
    }
    
    inline System::String^  Cliente::Dni::get() {
        return this->dniField;
    }
    inline System::Void Cliente::Dni::set(System::String^  value) {
        this->dniField = value;
    }
    
    inline System::String^  Cliente::Nombre::get() {
        return this->nombreField;
    }
    inline System::Void Cliente::Nombre::set(System::String^  value) {
        this->nombreField = value;
    }
    
    
    inline operarConVueltoCompletedEventArgs::operarConVueltoCompletedEventArgs(cli::array< System::Object^  >^  results, 
                System::Exception^  exception, System::Boolean cancelled, System::Object^  userState) : 
            System::ComponentModel::AsyncCompletedEventArgs(exception, cancelled, userState) {
        this->results = results;
    }
    
    inline WsVuelto::Respuesta^  operarConVueltoCompletedEventArgs::Result::get() {
        this->RaiseExceptionIfNecessary();
        return (cli::safe_cast<WsVuelto::Respuesta^  >(this->results[0]));
    }
    
    
    inline reversarAcreditacionVueltoCompletedEventArgs::reversarAcreditacionVueltoCompletedEventArgs(cli::array< System::Object^  >^  results, 
                System::Exception^  exception, System::Boolean cancelled, System::Object^  userState) : 
            System::ComponentModel::AsyncCompletedEventArgs(exception, cancelled, userState) {
        this->results = results;
    }
    
    inline WsVuelto::Respuesta^  reversarAcreditacionVueltoCompletedEventArgs::Result::get() {
        this->RaiseExceptionIfNecessary();
        return (cli::safe_cast<WsVuelto::Respuesta^  >(this->results[0]));
    }
    
    
    inline consultarAcreditacionesCompletedEventArgs::consultarAcreditacionesCompletedEventArgs(cli::array< System::Object^  >^  results, 
                System::Exception^  exception, System::Boolean cancelled, System::Object^  userState) : 
            System::ComponentModel::AsyncCompletedEventArgs(exception, cancelled, userState) {
        this->results = results;
    }
    
    inline cli::array< WsVuelto::Movimiento^  >^  consultarAcreditacionesCompletedEventArgs::Result::get() {
        this->RaiseExceptionIfNecessary();
        return (cli::safe_cast<cli::array< WsVuelto::Movimiento^  >^  >(this->results[0]));
    }
    
    
    inline consultarDebitosCompletedEventArgs::consultarDebitosCompletedEventArgs(cli::array< System::Object^  >^  results, 
                System::Exception^  exception, System::Boolean cancelled, System::Object^  userState) : 
            System::ComponentModel::AsyncCompletedEventArgs(exception, cancelled, userState) {
        this->results = results;
    }
    
    inline cli::array< WsVuelto::Movimiento^  >^  consultarDebitosCompletedEventArgs::Result::get() {
        this->RaiseExceptionIfNecessary();
        return (cli::safe_cast<cli::array< WsVuelto::Movimiento^  >^  >(this->results[0]));
    }
    
    
    inline GetDataCompletedEventArgs::GetDataCompletedEventArgs(cli::array< System::Object^  >^  results, System::Exception^  exception, 
                System::Boolean cancelled, System::Object^  userState) : 
            System::ComponentModel::AsyncCompletedEventArgs(exception, cancelled, userState) {
        this->results = results;
    }
    
    inline System::String^  GetDataCompletedEventArgs::Result::get() {
        this->RaiseExceptionIfNecessary();
        return (cli::safe_cast<System::String^  >(this->results[0]));
    }
}
